# Load or install packages
library(knitr)
library(rmdformats)
library(mapview)
library(viridis)
library(patchwork)
library(lubridate)
library(tidyverse)
library(ggrepel)
library(hrbrthemes)
library(data.table)
library(DT)
library(kableExtra)
library(here)
library(gt)
library(here)
library(quanteda)
library(quanteda.textmodels)
library(spacyr)
library(quanteda.textplots)
library(readtext)
library(stm)
library(tidytext)
library(wordcloud)
library("tidylog", warn.conflicts = FALSE)
library(magick)
library(showtext)
extrafont::loadfonts(device ='win')

# Specify your path here
source(here("/scripts/create_data_fundrise.R"))

# turn to tibble
all_text_df <- as_tibble(all_text_df)

#------------------#
# Create corpus ----
#------------------#

## Add dates format
all_text_df <-  all_text_df %>%
  mutate(YearMonth = format(as.POSIXct(datetime), "%Y-%m")) %>%
  mutate(Year = format(as.POSIXct(datetime), "%Y")) %>% 
  mutate(Day = format(as.POSIXct(datetime), "%Y-%m-%d"))


#organise dataframe in the hierarchical order of replies using the hierarchical structure of Reddit
# Function to convert text_id to numeric for sorting
convert_to_numeric <- function(reply) {
  reply_levels <- str_split(reply, "_")[[1]]
  numeric_value <- paste(sprintf("%05d", as.numeric(reply_levels)), collapse = "")
  return(numeric_value)
}

# Sort by thread_id and text_id (converted)
all_text_df <- all_text_df %>%
  mutate(numeric_reply = sapply(text_id, convert_to_numeric)) %>%
  arrange(thread_id, numeric_reply)

#Remove deleted comments
all_text_df <- all_text_df %>% 
  filter(!clean_text == "[deleted]") # deleted comments

#Remove urls in the text
all_text_df <- all_text_df %>% 
  mutate(clean_text = replace_url(clean_text)) 

#Remove lorem ipsum text generated by users / bots
all_text_df <- all_text_df %>% 
  filter(!grepl("lorem", clean_text)) %>% 
  filter(!grepl("perspiciatis", clean_text)) %>% 
  filter(!grepl("explicabo", clean_text)) %>% 
  filter(!grepl("inventore", clean_text))

#Remove a tale shared twice by a user/bot
all_text_df <- all_text_df %>% 
  filter(!grepl("Whiskers", clean_text)) 

#Remove a weird tale shared twice by a user
all_text_df <- all_text_df %>% 
  filter(!author == "AutoModerator")


#Remove characters like "----" and handles such as @this_user
all_text_df <- all_text_df %>% 
  mutate(clean_text = str_replace_all(clean_text, "--" ,"" )) %>% 
  mutate(clean_text = gsub("@[[:alnum:]_]+", "", clean_text))

#Replace words
all_text_df <- all_text_df %>% 
  #concatenate real estate into one single word
  mutate(clean_text = str_replace_all(clean_text, "real estate", "realestate")) %>%
  mutate(clean_text = str_replace_all(clean_text, "interest rates", "interestrates")) %>%
  mutate(clean_text = str_replace_all(clean_text, "Interest rates", "interestrates")) %>%
  mutate(clean_text = str_replace_all(clean_text, "Interest rate", "interestrates")) %>%
  mutate(clean_text = str_replace_all(clean_text, "IRS", "interestrates")) %>%
  mutate(clean_text = str_replace_all(clean_text, "interest rate", "interestrates")) %>%
  mutate(clean_text = str_replace_all(clean_text, "Interest Rate", "interestrates")) %>%
  
  #concatenate key expressions into one single word
  mutate(clean_text = str_replace_all(clean_text, "long term","longterm" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "tax bracket","taxbracket" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "long term growth","LTG" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "Long Term Growth","LTG" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "Long term growth","LTG" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "checking account","checkingaccount" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "tax season","taxseason" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "tax season","taxseason" ))  %>% #
  mutate(clean_text = str_replace_all(clean_text, "cap rates","caprate" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "cap rate","caprate" ))  %>% 
  
  #concatenate key entities into one single word
  mutate(clean_text = str_replace_all(clean_text, "interval fund", "Intervalfund" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "Interval Fund","Intervalfund" ))  %>% 
  mutate(clean_text = str_replace_all(clean_text, "Interval fund","Intervalfund" ))  %>% 
  mutate(clean_text = gsub("\\bInterval\\b", "Intervalfund", clean_text, ignore.case = TRUE)) %>% 
  mutate(clean_text = str_replace_all(clean_text, "S&P 500","S&P500" )) %>%  
  mutate(clean_text = str_replace_all(clean_text, "s&p 500","S&P500" )) %>%
  mutate(clean_text = str_replace_all(clean_text, "SP500","S&P500" )) %>%
  mutate(clean_text = str_replace_all(clean_text, "sp500","S&P500" )) %>%  
  mutate(clean_text = str_replace_all(clean_text, "s&p500","S&P500" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "(?i)Roth IRA","ROTHIRA" )) %>%
  mutate(clean_text = gsub("\\bira\\b", "IRA", clean_text, ignore.case = TRUE)) %>% 
  mutate(clean_text = gsub("\\bIRA\\b", "IRA", clean_text, ignore.case = TRUE)) %>% 
  mutate(clean_text = str_replace_all(clean_text, "Invitation Homes", "INVH")) %>%
  mutate(clean_text = str_replace_all(clean_text, "Silicon Valley Bank", "SVB")) %>%
  
  #Concatenate key locations into one single word
  mutate(clean_text = str_replace_all(clean_text, "San Francisco", "SanFrancisco")) %>%   mutate(clean_text = str_replace_all(clean_text, " SF ", " SanFrancisco ")) %>%
  mutate(clean_text = str_replace_all(clean_text, "San Fran", " SanFrancisco ")) %>%
  mutate(clean_text = str_replace_all(clean_text, " LA ", " LosAngeles ")) %>% 
  mutate(clean_text = str_replace_all(clean_text, "Los Angeles","LosAngeles" )) %>%  
  mutate(clean_text = str_replace_all(clean_text, "Las Vegas","LasVegas" )) %>%  
  mutate(clean_text = str_replace_all(clean_text, "sunbelt","Sunbelt" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "Sun Belt","Sunbelt" )) %>%
  mutate(clean_text = str_replace_all(clean_text, "San Antonio","SanAntonio" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "San Diego","SanDiego" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "San Jose","SanJose" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "East Coast","EastCoast" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "east coast","EastCoast" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "east Coast","EastCoast" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "West Coast","WestCoast" )) %>% 
  mutate(clean_text = str_replace_all(clean_text, "west coast","WestCoast" )) 


#Create one text by thread, merging all the comments in the conversation order
all_thread_df <-  all_text_df %>% 
  group_by(thread_id, url, title_clean) %>% 
  summarise(clean_text = paste0(clean_text, collapse = "\n"), # merge all comments
            date = unique(date[order_com==1]), 
            month = floor_date(ymd(date), "1 month")) %>% 
  ungroup() %>% 
  mutate(docnum = row_number()) 

#Prepare dataframe of threads with descriptive variables
all_thread_info <- all_text_df %>% 
  group_by(thread_id) %>% 
  summarise(clean_text = paste0(clean_text, collapse = "\n"), 
            n_authors = n_distinct(author), 
            n_comments = n(), 
            title_clean = unique(title_clean), url = unique(url), 
            date = unique(date[order_com==1]), 
            month = floor_date(ymd(date), "1 month"),
            timestamp = unique(timestamp[order_com==1]), 
            author =  unique(author[order_com==1])) %>% 
  ungroup() %>% 
  mutate(docnum = row_number())

# Create corpus
mycorpus <- corpus(all_thread_df, text_field = "clean_text") 

#------------------#
# Lemmatization ----
#------------------#

#Optional to activate / deactivate 

#1. Open corpus
# Specify your path here
# sparsed_corpus <-  readRDS(here("data/sparsed_corpus.RDS"))

#2.a Or run the whole process
## spacy_initialize()
# sparsed_corpus <- spacy_parse(mycorpus, 
#                               lemma = TRUE, 
#                               entity = T, 
#                               pos = T, 
#                               additional_attributes = c("like_num", "is_punct"))
# 
# sparsed_entity <- entity_extract(sparsed_corpus)
# spacy_finalize() #close to free memory


#2.b. Save sparsed corpus and open the saved file
# saveRDS(sparsed_corpus, file = "processed/sparsed_corpus.RDS")

#Clean sparsed corpus
number_to_remove <- c("one", "two", "three", "four", "five", "six", "seven",
                      "eight", "nine", "ten", "eleven", "twelve", "thirteen",
                      "fourteen", "fifteen", "sixteen", "seventeen", "nineteen",
                      "twenty")

# Fix inconsistencies for specific vocabularies, using lemmas
sparsed_corpus_clean <- sparsed_corpus %>% 
  mutate(lemma = ifelse(lemma == "HSA", "hsa", lemma)) %>% 
  
  mutate(lemma = ifelse(lemma == "mint", "Mint", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ACH", "ach", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ally", "Ally", lemma)) %>%
  mutate(lemma = ifelse(lemma == "ally.com", "Ally", lemma)) %>%
  mutate(lemma = ifelse(lemma == "ally.com", "Ally", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ira", "IRA", lemma)) %>%
  mutate(lemma = ifelse(lemma == "IRAS", "IRA", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "fidelity", "Fidelity", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ipo", "IPO", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "vc", "VC", lemma)) %>%
  mutate(lemma = ifelse(lemma == "VCs", "VC", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "reit", "REIT", lemma)) %>%
  mutate(lemma = ifelse(lemma == "REITS", "REIT", lemma)) %>%
  mutate(lemma = ifelse(lemma == "reits", "REIT", lemma)) %>%
  mutate(lemma = ifelse(lemma == "Reits", "REIT", lemma)) %>%
  mutate(lemma = ifelse(lemma == "REITS", "REIT", lemma)) %>%
  mutate(lemma = ifelse(lemma == "REITs", "REIT", lemma)) %>%
  
  mutate(lemma = ifelse(grepl("(?i)ereit", lemma), "eREIT", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "nav", "NAV", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "sfr", "SFR", lemma)) %>%
  mutate(lemma = ifelse(lemma == "SFRs", "SFR", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "plaid", "Plaid", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "evergrande", "Evergrande", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "equityzen", "EquityZen", lemma)) %>%
  mutate(lemma = ifelse(lemma == "Equityzen", "EquityZen", lemma)) %>%
  mutate(lemma = ifelse(lemma == "EquityZen.com", "EquityZen", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "fed", "FED", lemma)) %>%
  mutate(lemma = ifelse(lemma == "feds", "FED", lemma)) %>%
  mutate(lemma = ifelse(lemma == "Fed", "FED", lemma)) %>%
  mutate(lemma = ifelse(lemma == "Feds", "FED", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "vnq", "VNQ", lemma)) %>%
  mutate(lemma = ifelse(lemma == "Vanguards", "Vanguard", lemma)) %>%
  mutate(lemma = ifelse(lemma == "VANGUARD", "Vanguard", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "btr", "BTR", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "groundfloor", "Groundfloor", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "arrived", "Arrived", lemma)) %>%
  mutate(lemma = ifelse(lemma == "ARRIVED", "Arrived", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "Lex", "LEX", lemma)) %>%
  mutate(lemma = ifelse(lemma == "lex", "LEX", lemma)) %>%
  mutate(lemma = ifelse(lemma == "lex-markets.com", "LEX", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "cadre", "CADRE", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ArrivedHomes", "Arrived", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "crowdstreet", "Crowdstreet", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "capm", "CAPM", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "Syndication", "syndication", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ytd", "YTD", lemma)) %>% 
  
  mutate(lemma = ifelse(lemma == "Accredited", "accredited", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "Redemption", "redemption", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "Ytd", "YTD", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "iii", "III", lemma)) %>%
  
  mutate(lemma = ifelse(grepl("turbo", token), "TurboTax", lemma)) %>% 
  
  mutate(lemma = ifelse(grepl("401", lemma), "401k", lemma)) %>% 
  
  mutate(lemma = ifelse(grepl("1099", lemma), "1099div", lemma))%>%
  
  mutate(lemma = ifelse(grepl("k1", lemma), "k1", lemma)) %>% 
  mutate(lemma = ifelse(grepl("k1s", lemma), "k1", lemma)) %>% 
  mutate(lemma = ifelse(grepl("K1s", lemma), "k1", lemma)) %>% 
  mutate(lemma = ifelse(grepl("k-1", lemma), "k1", lemma)) %>% 
  mutate(lemma = ifelse(grepl("K-1s", lemma), "k1", lemma)) %>% 
  mutate(lemma = ifelse(grepl("K-1", lemma), "k1", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "taxis", "tax", lemma)) %>% 
  
  mutate(lemma = ifelse(lemma == "pende", "pending", lemma)) %>% 
  
  mutate(lemma = ifelse(lemma == "accredit", "accredited", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "reinveste", "reinvest", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "maxe", "maxing", lemma)) %>%
  
  mutate(lemma = ifelse(lemma == "ipos", "ipo", lemma)) %>%
  
  # Clean text
  filter(!is_punct == T) %>% 
  filter(!pos == "PART") %>% 
  filter(!pos == "SPACE") %>%
  filter(!lemma == "$") %>% 
  filter(!lemma == "$") %>% 
  filter(!lemma == ">") %>% 
  filter(!lemma == "=") %>% 
  filter(!lemma == "<") %>% 
  filter(!lemma == ".:il") %>% 
  filter(!lemma == "^^i") %>% 
  filter(!grepl("\\^\\^", lemma)) %>% 
  # filter(!(nchar(lemma) < 4 & pos == "NUM")) %>% 
  filter(!lemma %in% number_to_remove) %>% 
  filter(!lemma %in% seq(0, 100, 1))  

# CHeck example for one lemma
sparsed_corpus_clean %>% 
  filter(lemma == "invest") %>% 
  group_by(lemma, token, pos) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  as_tibble %>% 
  gt() %>% 
  cols_label(lemma = "lemma", token = "token", pos = "part of speech tag", n = "frequency") %>% 
  tab_header(
    title = "An example of lemmatization with 'invest' ") %>% 
  tab_options(table.width = "60%",  table.font.size = 10 ) %>% 
  opt_stylize(style = 2) 


#--------------------#
#  Tokenization ----
#--------------------#

## tokenize ----
tokens <- sparsed_corpus_clean %>% 
  as.tokens(use_lemma = T)


# Quick exploration
kwic(tokens,
     window = 5,
     pattern = ("algor*")) #use the * 

## stopwords ----

#We remove the stopwords, 
# using the dictionary [Stopword ISO](%22https://github.com/stopwords-iso/stopwords-iso%22), which contains 1298 words.

tokens <- tokens_remove(tokens, 
                        stopwords("en",
                                  source = "stopwords-iso"))


#---------------------#
# Create DFM ----
#--------------------#

## Create a DFM ----
dfm <- dfm(tokens) 

# CHeck top features
topfeatures(dfm, 30)

# Remove fundrise from the dfm
dfm <-  dfm_remove(dfm, pattern = "fundrise")


## Trimming the DFM ----
dfm_trim <- dfm_trim(dfm, min_docfreq = 0.005, max_docfreq = 0.99, 
                     docfreq_type = "prop", verbose = TRUE)
# Add metadata to the dfm
docvars(dfm_trim, "thread_id") <- all_thread_df$thread_id
docvars(dfm_trim, "month") <- all_thread_df$month

docvars(dfm, "thread_id") <- all_thread_df$thread_id
docvars(dfm, "month") <- all_thread_df$month

## Add time variable ----

# create a date formatted variable from the dataframe of threads
all_thread_df <- all_thread_df %>% 
  mutate(date_format = as.Date(date))

### For months ----
# Find the minimum date to determine the starting month
start_date <- min(all_thread_df$date_format)
start_month <- month(start_date)
# Create a new column 'month_num' to store the sequential count of months
all_thread_df$month_num <- (year(all_thread_df$date_format) - year(start_date)) * 12 + month(all_thread_df$date_format) - start_month + 1

### For weeks ----
year_week <- function(x,base) week(x) - week(base) + 52*(year(x) - year(base))
start_date <- min(all_thread_df$date_format)
# Calculate the week number based on the start date
all_thread_df$week_number <- floor(1 + abs(interval(all_thread_df$date_format, start_date)/weeks(1)))

### For days ----
all_thread_df <- all_thread_df %>% 
  mutate(day_num = as.numeric(dense_rank(date_format)))

#Add time variables to the dfm
docvars(dfm_trim, "month") <- all_thread_df$month_num
docvars(dfm_trim, "day") <- all_thread_df$day_num
docvars(dfm_trim, "week") <- all_thread_df$week_number
